# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: kube-state-metrics
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: kube-state-metrics
# subjects:
# - kind: ServiceAccount
#   name: kube-state-metrics
#   namespace: monitoring
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: kube-state-metrics
# rules:
# - apiGroups: [""]
#   resources:
#   - nodes
#   - pods
#   - services
#   - resourcequotas
#   - replicationcontrollers
#   - limitranges
#   verbs: ["list", "watch"]
# - apiGroups: ["extensions"]
#   resources:
#   - daemonsets
#   - deployments
#   - replicasets
#   verbs: ["list", "watch"]
# ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics
  namespace: monitoring
